language: python
services:
  - xvfb
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install -U pytest pytest-cov coveralls"
script:
  - pip install .
  - pytest --doctest-modules --cov=madic -v
after_success:
  - coveralls
